Added files for the new logo
shelcia/Bloggram pull request #499
Opened 2023-12-25 02:33 UTC by aindree-2005

closes #449

2023-12-26 05:59 UTC, shelcia requested changes
can you place them in public folder

2023-12-26 06:04 UTC, aindree-2005 commented
> can you place them in public folder

on it now

2023-12-26 06:07 UTC, aindree-2005 commented
@shelcia done

2023-12-27 00:06 UTC, shelcia approved these changes

2023-12-27 00:06 UTC, merged